# config.py —— 学生主要改这里:换站点 / 接自己下载的「上海城市数据集」
# ===========================================================================
# 1) 换站点:把 SLUG 改成下面 SITES 里的某个 slug,存档后在 notebook 重跑「准备」格。
# 2)（可选,进阶）自己建缓存:下载并解压「上海城市数据集」后,把 DATASET_ROOT 指过去,
#    跑「01_怎么选数据」notebook 的建缓存格,就能从原始多源数据亲手重建 data/<slug>/。
#    不填 DATASET_ROOT 也完全没问题:随包已带 3 站缓存,离线即可跑全部主流程。详见 数据集说明.md。
from pathlib import Path

SLUG = "lujiazui"  # 当前站点:改成 SITES 里任一 slug。换街道见 数据集说明.md「换成别的街道」。

DATASET_ROOT = "C:/baidunetdiskdownload/data_collection/上海城市数据集"  # (可选)你解压的「上海城市数据集」根目录(字符串路径),例:
#     DATASET_ROOT = "/Users/you/Downloads/上海城市数据集"
#   留 None = 用随包缓存(离线)。填了、且数据集在,才会从原始数据建新街道的缓存。

# 全市 229 个乡镇街道层单元(name=边界 shp 精确名、已校验)。改 SLUG 切换;研究单位=街道多边形,非方框。
# 三段:A 代表站 / B 已校验扩充站(均 ascii slug)/ C 其余全市(slug=中文名、可直接当 SLUG)。
# 仅 lujiazui/caoyang/yuyuan 随包带缓存;其余需 DATASET_ROOT 现建(已设)。详见 数据集说明.md。
SITES = [
    # ===== A. 代表站(ascii slug、含丰富 family;主册/报告默认)=====
    {"slug": "lujiazui", "name": "陆家嘴街道", "family": "资本/超高层"},
    {"slug": "caoyang", "name": "曹杨新村街道", "family": "单位/工人新村"},
    {"slug": "yuyuan", "name": "豫园街道", "family": "居民/里弄石库门"},
    {"slug": "waitan", "name": "外滩街道", "family": "资本/金融遗产"},
    {"slug": "nanjingxi", "name": "南京西路街道", "family": "资本/商业"},
    {"slug": "kongjiang", "name": "控江路街道", "family": "单位/工人新村"},
    {"slug": "pengpu", "name": "彭浦新村街道", "family": "单位/工人新村"},
    {"slug": "laoximen", "name": "老西门街道", "family": "居民/里弄石库门"},
    {"slug": "dapuqiao", "name": "打浦桥街道", "family": "居民/里弄+田子坊"},
    # ===== B. 已校验扩充站(ascii slug)=====
    {"slug": "xujiahui", "name": "徐家汇街道", "family": "资本/商业"},
    {"slug": "nanjingdong", "name": "南京东路街道", "family": "资本/商业核心"},
    {"slug": "beiwaitan", "name": "北外滩街道", "family": "资本/滨水更新"},
    {"slug": "wujiaochang", "name": "五角场街道", "family": "单位/高校知识"},
    {"slug": "quyang", "name": "曲阳路街道", "family": "单位/工人新村"},
    {"slug": "liangcheng", "name": "凉城新村街道", "family": "单位/工人新村"},
    {"slug": "fenglin", "name": "枫林路街道", "family": "单位/医教"},
    {"slug": "tianping", "name": "天平路街道", "family": "居民/历史风貌(花园洋房)"},
    {"slug": "xinhua", "name": "新华路街道", "family": "居民/历史风貌"},
    {"slug": "hunan", "name": "湖南路街道", "family": "居民/历史风貌(里弄+洋房)"},
    {"slug": "jiangning", "name": "江宁路街道", "family": "居民/里弄"},
    {"slug": "ruijin2", "name": "瑞金二路街道", "family": "居民/历史风貌"},
    # ===== C. 全市其余乡镇街道(slug=中文名、可直接当 SLUG;family=行政层级)=====
    {"slug": "半淞园路街道", "name": "半淞园路街道", "family": "街道"},
    {"slug": "小东门街道", "name": "小东门街道", "family": "街道"},
    {"slug": "五里桥街道", "name": "五里桥街道", "family": "街道"},
    {"slug": "淮海中路街道", "name": "淮海中路街道", "family": "街道"},
    {"slug": "斜土路街道", "name": "斜土路街道", "family": "街道"},
    {"slug": "长桥街道", "name": "长桥街道", "family": "街道"},
    {"slug": "田林街道", "name": "田林街道", "family": "街道"},
    {"slug": "虹梅路街道", "name": "虹梅路街道", "family": "街道"},
    {"slug": "康健新村街道", "name": "康健新村街道", "family": "街道"},
    {"slug": "凌云路街道", "name": "凌云路街道", "family": "街道"},
    {"slug": "龙华街道", "name": "龙华街道", "family": "街道"},
    {"slug": "漕河泾街道", "name": "漕河泾街道", "family": "街道"},
    {"slug": "华泾镇", "name": "华泾镇", "family": "镇"},
    {"slug": "漕河泾新兴技术开发区", "name": "漕河泾新兴技术开发区", "family": "其它"},
    {"slug": "华阳路街道", "name": "华阳路街道", "family": "街道"},
    {"slug": "江苏路街道", "name": "江苏路街道", "family": "街道"},
    {"slug": "周家桥街道", "name": "周家桥街道", "family": "街道"},
    {"slug": "天山路街道", "name": "天山路街道", "family": "街道"},
    {"slug": "仙霞新村街道", "name": "仙霞新村街道", "family": "街道"},
    {"slug": "虹桥街道", "name": "虹桥街道", "family": "街道"},
    {"slug": "程家桥街道", "name": "程家桥街道", "family": "街道"},
    {"slug": "北新泾街道", "name": "北新泾街道", "family": "街道"},
    {"slug": "新泾镇", "name": "新泾镇", "family": "镇"},
    {"slug": "石门二路街道", "name": "石门二路街道", "family": "街道"},
    {"slug": "静安寺街道", "name": "静安寺街道", "family": "街道"},
    {"slug": "曹家渡街道", "name": "曹家渡街道", "family": "街道"},
    {"slug": "天目西路街道", "name": "天目西路街道", "family": "街道"},
    {"slug": "北站街道", "name": "北站街道", "family": "街道"},
    {"slug": "宝山路街道", "name": "宝山路街道", "family": "街道"},
    {"slug": "共和新路街道", "name": "共和新路街道", "family": "街道"},
    {"slug": "大宁路街道", "name": "大宁路街道", "family": "街道"},
    {"slug": "临汾路街道", "name": "临汾路街道", "family": "街道"},
    {"slug": "芷江西路街道", "name": "芷江西路街道", "family": "街道"},
    {"slug": "彭浦镇", "name": "彭浦镇", "family": "镇"},
    {"slug": "长风新村街道", "name": "长风新村街道", "family": "街道"},
    {"slug": "长寿路街道", "name": "长寿路街道", "family": "街道"},
    {"slug": "甘泉路街道", "name": "甘泉路街道", "family": "街道"},
    {"slug": "石泉路街道", "name": "石泉路街道", "family": "街道"},
    {"slug": "宜川路街道", "name": "宜川路街道", "family": "街道"},
    {"slug": "万里街道", "name": "万里街道", "family": "街道"},
    {"slug": "真如镇街道", "name": "真如镇街道", "family": "街道"},
    {"slug": "长征镇", "name": "长征镇", "family": "镇"},
    {"slug": "桃浦镇", "name": "桃浦镇", "family": "镇"},
    {"slug": "欧阳路街道", "name": "欧阳路街道", "family": "街道"},
    {"slug": "广中路街道", "name": "广中路街道", "family": "街道"},
    {"slug": "嘉兴路街道", "name": "嘉兴路街道", "family": "街道"},
    {"slug": "四川北路街道", "name": "四川北路街道", "family": "街道"},
    {"slug": "江湾镇街道", "name": "江湾镇街道", "family": "街道"},
    {"slug": "定海路街道", "name": "定海路街道", "family": "街道"},
    {"slug": "平凉路街道", "name": "平凉路街道", "family": "街道"},
    {"slug": "江浦路街道", "name": "江浦路街道", "family": "街道"},
    {"slug": "四平路街道", "name": "四平路街道", "family": "街道"},
    {"slug": "长白新村街道", "name": "长白新村街道", "family": "街道"},
    {"slug": "延吉新村街道", "name": "延吉新村街道", "family": "街道"},
    {"slug": "殷行街道", "name": "殷行街道", "family": "街道"},
    {"slug": "大桥街道", "name": "大桥街道", "family": "街道"},
    {"slug": "新江湾城街道", "name": "新江湾城街道", "family": "街道"},
    {"slug": "五角场镇", "name": "五角场镇", "family": "镇"},
    {"slug": "江川路街道", "name": "江川路街道", "family": "街道"},
    {"slug": "古美街道", "name": "古美街道", "family": "街道"},
    {"slug": "新虹街道", "name": "新虹街道", "family": "街道"},
    {"slug": "浦锦街道", "name": "浦锦街道", "family": "街道"},
    {"slug": "莘庄镇", "name": "莘庄镇", "family": "镇"},
    {"slug": "七宝镇", "name": "七宝镇", "family": "镇"},
    {"slug": "颛桥镇", "name": "颛桥镇", "family": "镇"},
    {"slug": "华漕镇", "name": "华漕镇", "family": "镇"},
    {"slug": "虹桥镇", "name": "虹桥镇", "family": "镇"},
    {"slug": "梅陇镇", "name": "梅陇镇", "family": "镇"},
    {"slug": "吴泾镇", "name": "吴泾镇", "family": "镇"},
    {"slug": "马桥镇", "name": "马桥镇", "family": "镇"},
    {"slug": "浦江镇", "name": "浦江镇", "family": "镇"},
    {"slug": "莘庄工业区", "name": "莘庄工业区", "family": "其它"},
    {"slug": "友谊路街道", "name": "友谊路街道", "family": "街道"},
    {"slug": "吴淞街道", "name": "吴淞街道", "family": "街道"},
    {"slug": "张庙街道", "name": "张庙街道", "family": "街道"},
    {"slug": "罗店镇", "name": "罗店镇", "family": "镇"},
    {"slug": "大场镇", "name": "大场镇", "family": "镇"},
    {"slug": "杨行镇", "name": "杨行镇", "family": "镇"},
    {"slug": "月浦镇", "name": "月浦镇", "family": "镇"},
    {"slug": "罗泾镇", "name": "罗泾镇", "family": "镇"},
    {"slug": "顾村镇", "name": "顾村镇", "family": "镇"},
    {"slug": "高境镇", "name": "高境镇", "family": "镇"},
    {"slug": "庙行镇", "name": "庙行镇", "family": "镇"},
    {"slug": "淞南镇", "name": "淞南镇", "family": "镇"},
    {"slug": "宝山城市工业园区", "name": "宝山城市工业园区", "family": "其它"},
    {"slug": "新成路街道", "name": "新成路街道", "family": "街道"},
    {"slug": "真新街道", "name": "真新街道", "family": "街道"},
    {"slug": "菊园新区管委会", "name": "菊园新区管委会", "family": "其它"},
    {"slug": "嘉定镇街道", "name": "嘉定镇街道", "family": "街道"},
    {"slug": "南翔镇", "name": "南翔镇", "family": "镇"},
    {"slug": "安亭镇", "name": "安亭镇", "family": "镇"},
    {"slug": "马陆镇", "name": "马陆镇", "family": "镇"},
    {"slug": "徐行镇", "name": "徐行镇", "family": "镇"},
    {"slug": "华亭镇", "name": "华亭镇", "family": "镇"},
    {"slug": "外冈镇", "name": "外冈镇", "family": "镇"},
    {"slug": "江桥镇", "name": "江桥镇", "family": "镇"},
    {"slug": "嘉定工业区", "name": "嘉定工业区", "family": "其它"},
    {"slug": "潍坊新村街道", "name": "潍坊新村街道", "family": "街道"},
    {"slug": "周家渡街道", "name": "周家渡街道", "family": "街道"},
    {"slug": "塘桥街道", "name": "塘桥街道", "family": "街道"},
    {"slug": "上钢新村街道", "name": "上钢新村街道", "family": "街道"},
    {"slug": "南码头路街道", "name": "南码头路街道", "family": "街道"},
    {"slug": "沪东新村街道", "name": "沪东新村街道", "family": "街道"},
    {"slug": "金杨新村街道", "name": "金杨新村街道", "family": "街道"},
    {"slug": "洋泾街道", "name": "洋泾街道", "family": "街道"},
    {"slug": "浦兴路街道", "name": "浦兴路街道", "family": "街道"},
    {"slug": "东明路街道", "name": "东明路街道", "family": "街道"},
    {"slug": "花木街道", "name": "花木街道", "family": "街道"},
    {"slug": "川沙新镇", "name": "川沙新镇", "family": "镇"},
    {"slug": "高桥镇", "name": "高桥镇", "family": "镇"},
    {"slug": "北蔡镇", "name": "北蔡镇", "family": "镇"},
    {"slug": "合庆镇", "name": "合庆镇", "family": "镇"},
    {"slug": "唐镇", "name": "唐镇", "family": "镇"},
    {"slug": "曹路镇", "name": "曹路镇", "family": "镇"},
    {"slug": "金桥镇", "name": "金桥镇", "family": "镇"},
    {"slug": "高行镇", "name": "高行镇", "family": "镇"},
    {"slug": "高东镇", "name": "高东镇", "family": "镇"},
    {"slug": "张江镇", "name": "张江镇", "family": "镇"},
    {"slug": "三林镇", "name": "三林镇", "family": "镇"},
    {"slug": "惠南镇", "name": "惠南镇", "family": "镇"},
    {"slug": "周浦镇", "name": "周浦镇", "family": "镇"},
    {"slug": "新场镇", "name": "新场镇", "family": "镇"},
    {"slug": "大团镇", "name": "大团镇", "family": "镇"},
    {"slug": "康桥镇", "name": "康桥镇", "family": "镇"},
    {"slug": "航头镇", "name": "航头镇", "family": "镇"},
    {"slug": "泥城镇", "name": "泥城镇", "family": "镇"},
    {"slug": "宣桥镇", "name": "宣桥镇", "family": "镇"},
    {"slug": "书院镇", "name": "书院镇", "family": "镇"},
    {"slug": "万祥镇", "name": "万祥镇", "family": "镇"},
    {"slug": "老港镇", "name": "老港镇", "family": "镇"},
    {"slug": "南汇新城镇", "name": "南汇新城镇", "family": "镇"},
    {"slug": "中国（上海）自由贸易试验区（保税片区）", "name": "中国（上海）自由贸易试验区（保税片区）", "family": "其它"},
    {"slug": "金桥经济技术开发区", "name": "金桥经济技术开发区", "family": "其它"},
    {"slug": "张江高科技园区", "name": "张江高科技园区", "family": "其它"},
    {"slug": "石化街道", "name": "石化街道", "family": "街道"},
    {"slug": "朱泾镇", "name": "朱泾镇", "family": "镇"},
    {"slug": "枫泾镇", "name": "枫泾镇", "family": "镇"},
    {"slug": "张堰镇", "name": "张堰镇", "family": "镇"},
    {"slug": "亭林镇", "name": "亭林镇", "family": "镇"},
    {"slug": "吕巷镇", "name": "吕巷镇", "family": "镇"},
    {"slug": "廊下镇", "name": "廊下镇", "family": "镇"},
    {"slug": "金山卫镇", "name": "金山卫镇", "family": "镇"},
    {"slug": "漕泾镇", "name": "漕泾镇", "family": "镇"},
    {"slug": "山阳镇", "name": "山阳镇", "family": "镇"},
    {"slug": "金山工业区", "name": "金山工业区", "family": "其它"},
    {"slug": "岳阳街道", "name": "岳阳街道", "family": "街道"},
    {"slug": "永丰街道", "name": "永丰街道", "family": "街道"},
    {"slug": "方松街道", "name": "方松街道", "family": "街道"},
    {"slug": "中山街道", "name": "中山街道", "family": "街道"},
    {"slug": "广富林街道", "name": "广富林街道", "family": "街道"},
    {"slug": "九里亭街道", "name": "九里亭街道", "family": "街道"},
    {"slug": "泗泾镇", "name": "泗泾镇", "family": "镇"},
    {"slug": "佘山镇", "name": "佘山镇", "family": "镇"},
    {"slug": "车墩镇", "name": "车墩镇", "family": "镇"},
    {"slug": "新桥镇", "name": "新桥镇", "family": "镇"},
    {"slug": "洞泾镇", "name": "洞泾镇", "family": "镇"},
    {"slug": "九亭镇", "name": "九亭镇", "family": "镇"},
    {"slug": "泖港镇", "name": "泖港镇", "family": "镇"},
    {"slug": "石湖荡镇", "name": "石湖荡镇", "family": "镇"},
    {"slug": "新浜镇", "name": "新浜镇", "family": "镇"},
    {"slug": "叶榭镇", "name": "叶榭镇", "family": "镇"},
    {"slug": "小昆山镇", "name": "小昆山镇", "family": "镇"},
    {"slug": "松江工业区", "name": "松江工业区", "family": "其它"},
    {"slug": "夏阳街道", "name": "夏阳街道", "family": "街道"},
    {"slug": "盈浦街道", "name": "盈浦街道", "family": "街道"},
    {"slug": "香花桥街道", "name": "香花桥街道", "family": "街道"},
    {"slug": "朱家角镇", "name": "朱家角镇", "family": "镇"},
    {"slug": "练塘镇", "name": "练塘镇", "family": "镇"},
    {"slug": "金泽镇", "name": "金泽镇", "family": "镇"},
    {"slug": "赵巷镇", "name": "赵巷镇", "family": "镇"},
    {"slug": "徐泾镇", "name": "徐泾镇", "family": "镇"},
    {"slug": "华新镇", "name": "华新镇", "family": "镇"},
    {"slug": "重固镇", "name": "重固镇", "family": "镇"},
    {"slug": "白鹤镇", "name": "白鹤镇", "family": "镇"},
    {"slug": "西渡街道", "name": "西渡街道", "family": "街道"},
    {"slug": "奉浦街道", "name": "奉浦街道", "family": "街道"},
    {"slug": "南桥镇", "name": "南桥镇", "family": "镇"},
    {"slug": "奉城镇", "name": "奉城镇", "family": "镇"},
    {"slug": "庄行镇", "name": "庄行镇", "family": "镇"},
    {"slug": "金汇镇", "name": "金汇镇", "family": "镇"},
    {"slug": "四团镇", "name": "四团镇", "family": "镇"},
    {"slug": "青村镇", "name": "青村镇", "family": "镇"},
    {"slug": "柘林镇", "name": "柘林镇", "family": "镇"},
    {"slug": "海湾镇", "name": "海湾镇", "family": "镇"},
    {"slug": "上海市奉贤区海湾旅游区", "name": "上海市奉贤区海湾旅游区", "family": "其它"},
    {"slug": "金海社区", "name": "金海社区", "family": "其它"},
    {"slug": "城桥镇", "name": "城桥镇", "family": "镇"},
    {"slug": "堡镇", "name": "堡镇", "family": "镇"},
    {"slug": "新河镇", "name": "新河镇", "family": "镇"},
    {"slug": "庙镇", "name": "庙镇", "family": "镇"},
    {"slug": "竖新镇", "name": "竖新镇", "family": "镇"},
    {"slug": "向化镇", "name": "向化镇", "family": "镇"},
    {"slug": "三星镇", "name": "三星镇", "family": "镇"},
    {"slug": "港沿镇", "name": "港沿镇", "family": "镇"},
    {"slug": "中兴镇", "name": "中兴镇", "family": "镇"},
    {"slug": "陈家镇", "name": "陈家镇", "family": "镇"},
    {"slug": "绿华镇", "name": "绿华镇", "family": "镇"},
    {"slug": "港西镇", "name": "港西镇", "family": "镇"},
    {"slug": "建设镇", "name": "建设镇", "family": "镇"},
    {"slug": "新海镇", "name": "新海镇", "family": "镇"},
    {"slug": "东平镇", "name": "东平镇", "family": "镇"},
    {"slug": "长兴镇", "name": "长兴镇", "family": "镇"},
    {"slug": "新村乡", "name": "新村乡", "family": "乡"},
    {"slug": "横沙乡", "name": "横沙乡", "family": "乡"},
    {"slug": "前卫农场", "name": "前卫农场", "family": "其它"},
    {"slug": "东平林场", "name": "东平林场", "family": "其它"},
    {"slug": "上实现代农业园区", "name": "上实现代农业园区", "family": "其它"},
    {"slug": "祝桥镇", "name": "祝桥镇", "family": "镇"},
]

# 默认示范的 3 站(其余街道改 SLUG 即可离线切;06 的 build_canvas 也默认跑这 3 站)。
REPORT_SITES = ["lujiazui", "caoyang", "yuyuan"]

# ===== 以下自动推导,通常不用改 =====
UTM = 32651  # 上海 UTM 51N(几何度量 / 挤体用米)


def site_name(slug=None):
    """slug → 街道精确名。先查 SITES;查不到再回退读 data/<slug>/site.yaml(让换地方建的新街道也能取名)。"""
    slug = slug or SLUG
    for s in SITES:
        if s["slug"] == slug:
            return s["name"]
    try:
        import yaml
        from pathlib import Path

        return yaml.safe_load(
            open(
                Path(__file__).resolve().parent / "data" / slug / "site.yaml",
                encoding="utf-8",
            )
        )["name"]
    except Exception:
        raise ValueError(
            "未知 slug:%s(不在 SITES,也没有 data/%s/ 缓存)。见 数据集说明.md「换成别的街道」。"
            % (slug, slug)
        )
